spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datacat
    username: root
    password: Password@123

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
  security:
    okta:
      oauth2:
        issuer: "https://dev-05002749.okta.com/oauth2/default"
        client-id: "0oa74n9k7vsIxyEl45d7"
        client-secret: "zHF3w0Jg8VLXTHnIu512tIX8BquEtAcN1NaYxcjE"

